version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - TZ=${TIMEZONE}
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ${WEB_ROOT_PATH}:/var/www/
      - ${NGINX_LOG_PATH}:/var/log/nginx/
    command: >
      /bin/bash -c "chmod -R 755 /var/www && 
                    chown -R www-data:www-data /var/www && 
                    nginx -g 'daemon off;'"
    depends_on:
      - php
      - mariadb
    networks:
      - backend
  
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ${WEB_ROOT_PATH}/certbot/:/var/www/certbot/:rw
  #     - ./nginx/ssl/:/etc/letsencrypt/:rw
  #   networks:
  #     - backend

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - TZ=${TIMEZONE}
    volumes:
      - ${MYSQL_CONF_PATH}:/etc/mysql/conf.d/docker.cnf
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - TZ=${TIMEZONE}
    command: redis-server /etc/redis/redis.conf
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONF_PATH}:/etc/redis/redis.conf
    networks:
      - backend

  php:
    build:
      context: ./php
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=false
        - EXT_PROTOBUF=fals
        - EXT_MEMCACHED=false
        - EXT_SWOOLED=false
    container_name: php
    restart: always
    environment:
      - TZ=${TIMEZONE}
    ports:
      - "9081:9081"
      - "8881:8881"
    volumes:
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
      - ./php/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/config/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./id_rsa.pub:/root/.ssh/id_rsa.pub
      - ./id_rsa:/root/.ssh/id_rsa
      - ${WEB_ROOT_PATH}:/var/www/
      - ./logs/php/:/var/log/php/
      - ./logs/app/:/data/log/
    depends_on:
      - mariadb
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge


